#!/bin/bash
#SBATCH --qos=edge
#SBATCH -n 8
#SBATCH -t 4-00:00:00
#SBATCH -J PYRIDINE-MINUS-MODE-01/

mpirun -n 8 /home/grayj6/data/cp2k-7.1/exe/local/cp2k.popt  -o Vibration-Pyridine.out GEO-OPT.inp
